### ISSUE TITLE
Remove git repos from `package.json`

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1032]
IMO it's better to stay up-to-date with the actual dependency *or* commit to maintaining our own module if actually necessary.

- [ ] github:mmckegg/flumedb#add-await-ready-option
- [ ] github:mmckegg/mutant#intersection-binding-viewport
- [ ] github:ssbc/ssb-about#use-await-ready
- [ ] github:mmckegg/suggest-box#scroll-selection-into-view
- [ ] github:ssbc/ssb-config#auto-config-incoming

**Comment by mmckegg** [comment]
I think that the [mutant one](https://github.com/mmckegg/mutant/pull/25) is probably safe to merge now! We haven't had any problems with that.

The flumedb one should actually be using @dominictarr's implementation of this: https://github.com/flumedb/flumedb/pull/24 (but that hasn't been merged either). And with that change, we should be merging: https://github.com/ssbc/ssb-about/tree/use-since (which addresses the about one).

Not sure about suggest box. Maybe talk Paul into moving that repo, or we could just do our own ssbc fork.
