### ISSUE TITLE
Switching from "most active" to "recent" in tags freezes app for several minutes on OSX

### ISSUE THREAD

**Issue by HendrikPetertje** [ssbc/patchwork#1037]
Hey there, Lemme first say that I absolutely love the Patchwork app and appreciate the enormous effort all of you have put in it so far!
I'll describe my problem in some kind of readable format:

re-produce:
- Click on "more>" menu in the top and hit "tags",
- In the tags window click on the tab "From Everyone"
- A spinner shows up in the top of the screen with "Scuttling", the app remains usable and clickable during this "scuttling".
- In the side-bar I switch from "Most Active" to "Recent"
- The interface freezes for 2 minutes or so, I can't navigate and the cursor remains a pointer.
- After 2 minutes the Recent tab becomes highlighted and I see the "Scuttling" animation at the top of the screen.
- Posts start to load.

What I expected:
Clicking Recent not freezing the interface

What happend:
The interface frooze.

Verison information:
- OSX Mojave, version 10.14.4 on a Macbook pro (15-inch 2017)
- Patchwork v3.12.0-beta.2 (happens on Patchwork v3.12.0-beta.0 too)
- gossip.json size: 393kb
- total SSB size: 7.1 gb

**Comment by HendrikPetertje** [comment]
tabbing back to "most active" yields the same results.

**Comment by christianbundy** [comment]
Thanks for the awesome bug report! My intuition is that there's probably a bottleneck happening in scuttle-tag or the code around it. The code in #887 *might* fix this, but I haven't had time to test that branch.

**Comment by black-puppydog** [comment]
Re-opening this because in the course of debugging #1337 I stumbled over it.
For me this happens both on `master`, on the two most recent AppImages, and on that PR.
And even though I have left it in that state for long times (hours) it has never finished.
However, it only happens with my main identity. With smaller test identities it also doesn't happen on any of the aforementioned versions.

Since I didn't know about this issue it took me some time to figure this out; I thought something had silently crashed.
In the end, I decided to limit the number of tags involved, simply by adding `.slice(0, 10)` to this line:

https://github.com/ssbc/scuttle-tag/blob/cc007759a338d67035f7a68e42a054b6a36d8143/obs.js#L214

That "fixes" the issue. So it seems like nothing is fundamentally broken, but there is definitely a performance issue. I suspect that some operation has a polynomial factor we didn't realize, otherwise it would work (albeit very slowly) for my main identity.

**Comment by black-puppydog** [comment]
I just ran this with the electron profiling tools attached and noticed that the rendering processes (shown below the flamegraph) take up most of this time. Here's a trace: [Profile-20210205T093329.json.gz](https://github.com/ssbc/patchwork/files/5931151/Profile-20210205T093329.json.gz)
![image](https://user-images.githubusercontent.com/189241/107009786-c81c0680-6795-11eb-9d52-f56e30e3e751.png)

What you're seeing is me opening the tags page, **then** starting the profiler, and clicking on "recent".
Not sure why there's two nested tasks there, but the bulk of them seems to be taken up by "layout". That's honestly not what I had thought this would be. I'm not adept at reading these traces, but Layout would imply that the data is correctly returned from ssb-server/mutant, but arranging all the tag boxes is taking time?

**Comment by black-puppydog** [comment]
![image](https://user-images.githubusercontent.com/189241/107010106-3365d880-6796-11eb-8e37-db825a1e3a7e.png)

also not sure if these "rasterize paint" jobs are normal like that.
