### ISSUE TITLE
The view sometimes gets scrolled out of view when writing messages

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1066]
How to reproduce:
* Open a thread
* Scroll to the bottom and start writing a reply
* Press pageup on your keyboard
* The entire page (including the top bar) should scroll up (opposite direction of what you would expect from pageup) leaving you only seeing the text box you were writing in. You can still scroll and interact, but only within that small area. Only way I've found to fix it is to restart patchwork or ctrl-r.

**Comment by christianbundy** [comment]
See also: https://github.com/ssbc/patchbay/issues/268

**Comment by Powersource** [comment]
Reproduced by @cblgh just now :P

**Comment by christianbundy** [comment]
>  Powersource assigned hermes-bot and unassigned Powersource 44 minutes ago 

?

**Comment by Powersource** [comment]
Idk, to pin it but make it clear no one in particular is taking it on

**Comment by christianbundy** [comment]
(FWIW I'd *personally* like to avoid pinning issues that don't have anyone taking responsibility for them, but I won't stop you from doing it.)

**Comment by christianbundy** [comment]
I just reread my above message and it had kind of a stern tone. Hmm. I meant it in a playful "not my style, but we don't have to have the same style" kind of way. Hope that's more clear and not a weird "you have violated my sacred preferences" kinda way.

TEXT IS HARD

**Comment by Powersource** [comment]
For e.g. this issue no one is really 'taking responsibility' for it (and I think that probably applies to most of the issues with someone assigned to them), but for me this felt like enough of a bug that I wouldn't want stalebot to sweep it away.

But my opinion here isn't super strong, was mostly trying to clean up old issues.

**Comment by christianbundy** [comment]
Maybe "taking responsibility" is the wrong vibe. My preference is to assign myself to issues that I want open, that way there's no ambiguity about who is insisting on keeping the issue open. I don't like "pinned" because in 5 years it will remain open and unless we have a conversation like this, it's unclear whether someone actually wants it to remain open for 5 years or whether someone was annoyed with stalebot and labeled "pinned".

My issue management philosophy is that open issues should be active, and that 'closed' is more like "no longer active". :shrug: GitHub issue management isn't ideal at all.
