### ISSUE TITLE
Border radius inconsistent between themes

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#1082]
See also: #1074 

I think `border-radius` declaration should always be set in the base theme. Here's what I'm seeing instead:

```console
$ git grep border-radius
base/avatar.mcss:  border-radius: 3px
base/base.mcss:    border-radius: 0
base/button.mcss:  border-radius: 3px
base/feed-meta-summary.mcss:    border-radius: 3px
base/feed-meta-summary.mcss:        border-radius: 3px
base/feed-meta-summary.mcss:          border-radius: 3px
base/main-window.mcss:        border-radius: 3px
base/main-window.mcss:        border-radius: 3px
base/main-window.mcss:        border-radius: 10px
base/message.mcss:    border-radius: 3px
base/message.mcss:        border-radius: 3px
base/profile-list.mcss:        border-radius: 10px
base/tag.mcss:  border-radius: 2px
base/taggers-list.mcss:        border-radius: 10px
base/toggle-button.mcss:  border-radius: 3px
dark/all-channels.mcss:    border-radius: 3px
dark/all-channels.mcss:      border-radius: 3px
dark/channel-list.mcss:    border-radius: 3px
dark/channel-list.mcss:      border-radius: 3px
dark/compose.mcss:  border-radius: 3px
dark/gathering-card.mcss:        border-radius: 3px
dark/image-input.mcss:    border-radius: 3px
dark/main-window.mcss:        border-radius: 10px
dark/main-window.mcss:        border-radius: 10px
dark/main-window.mcss:        border-radius: 3px
dark/markdown.mcss:      border-radius: 3px
dark/picker.mcss:    border-radius: 3px
dark/picker.mcss:      border-radius: 3px
dark/picker.mcss:    border-radius: 3px
dark/profile-header.mcss:      border-radius: 3px
dark/profile-list.mcss:    border-radius: 3px
dark/profile-list.mcss:        border-radius: 3px
dark/profile-preview.mcss:  border-radius: 3px
dark/tag-list.mcss:    border-radius: 3px
dark/taggers-list.mcss:    border-radius: 3px
light/all-channels.mcss:    border-radius: 5px
light/all-channels.mcss:      border-radius: 4px
light/channel-list.mcss:    border-radius: 5px
light/channel-list.mcss:      border-radius: 4px
light/compose.mcss:        border-radius: 4px
light/image-input.mcss:    border-radius: 5px
light/main-window.mcss:        border-radius: 2px
light/profile-list.mcss:    border-radius: 5px
light/tag-list.mcss:    border-radius: 5px
light/taggers-list.mcss:    border-radius: 5px
```

**Comment by foopod** [comment]
I am quite keen to start contributing to Patchwork. And this seems like a great issue to start with.

I have already had a look at the code base a bit. Looks like it always uses the base styles, then applies light or dark over the top of this.

I can move these rules into the base styles. However there are some conflicts, e.g. all-channels.mcss (3px and 5px), in these cases we could...

+ Take the average, 4px in the example.
+ Decide on a common border-radius, perhaps 5px since (and this is an assumption) the majority of users don't change the theme and are using light.
+ Keep these theme specific.

**Comment by foopod** [comment]
While doing this I noticed some other bits and pieces...

+ Rules that are no longer used. e.g. in all-channels.mcss it looks like AllChannels > a.channel > a is for an older version of lib/depject/page/html/render/channels.js.
+ There are inconsistencies for border-radius in base. If we are happy with 5px, I can clean that up too.
+ There is styling in dark for [main-window.mcss](https://github.com/ssbc/patchwork/commit/08d3127203ab8e7500aba6fcdd7343ef094146d3), some of which is colour, but the width and border-radius here should perhaps also be moved to base.

I suppose a larger piece of work going forward might be to consolidate the css so that the only rules in dark/light are for colour changes?
