### ISSUE TITLE
Replace infinite scrolling with a "Show more" button

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1109]
People always go on about how infinite scrolling is horrible. I think this solution could be a simple way of reducing the distract-iness of patchwork (even if it's still not as good as I hope it can be, but that might require writing a new client).

**Comment by cinnamon-bun** [comment]
Possible specs for this:
* "Load More" button after 20 posts.  Click it to expand the current page by another 20.  Not exactly pagination but it gives the user moments of choice where they can decide to stop reading
* A setting to turn this on/off
* Consider keyboard users - a keyboard shortcut for Load More?

The Mastodon client [Pinafore](https://pinafore.social) calls things like this ["wellness settings"](https://github.com/nolanlawson/pinafore/pull/1256).  Other wellness settings could be Disable Images, Don't Animate Images, Grayscale Mode, Hide Engagement Numbers, etc

**Comment by dangerousbeans** [comment]
nooooooo

**Comment by Powersource** [comment]
> "Load More" button after 20 posts.

Sounds like a good idea, gets rid of the problem but minimizes clicking. Guessing this is easier to implement as well.

> A setting to turn this on/off

UX guidelines say to minimize the amount of settings. I would prefer a clean design where we don't feel we need the setting.

> Consider keyboard users

We (sadly) [don't support keyboard users](https://github.com/ssbc/patchwork/issues/793) as it is, I think this is a concern we should handle in another issue.

> nooooooo

lol mind elaborating?

**Comment by cinnamon-bun** [comment]
Without a toggle setting or keyboard support, it would be a regression for people like me who use the mouse as little as possible because of carpal tunnel etc.

I feel that settings are appropriate for accessibility-type settings since each person has unique needs and capabilities.  Like in a car, you don't need to adjust the engine settings but you do need to adjust the seat since people are different sizes.  Though if we can find a way to meet more needs with fewer settings that's better (universal design).

A key event handler wouldn't be too hard, but it would have to check if the compose window was focused to avoid triggering when you're writing a post.  I volunteer to write the key handler :)

**Comment by trosel** [comment]
I'll propose this as a possible solution too:

![image](https://user-images.githubusercontent.com/1299322/65426410-3305b100-ddde-11e9-92aa-1859bfa2fcc7.png)

On instagram, this gets inserted into the timeline in between posts when you get to the posts that you've already seen.

Pagination could be seen as a step backward (at least technologically). This could be a wellness addition that doesn't hinder the nice infinite scrolling behavior itself.

**Comment by black-puppydog** [comment]
wow, just seeing that icon there as a screenshot makes me feel very comfy. I'm in favour of this :)
