### ISSUE TITLE
Indicate sync state with the network

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#113]
It would be handy if Patchwork told you whether you've synced your latest updates to peers. That way you know when it's safe to close your laptop after making a post.

**Comment by itsrachelfish** [comment]
It would also be nice if there was a progress bar when downloading images. My friend sent me an image and all it says is "Fetching image". I've been sitting here with my client open for 20 minutes and it still hasn't loaded.

Is the image still loading? Did my friend disconnect before it was finished uploading? I have no idea!

**Comment by mmckegg** [comment]
@itsrachelfish Yeah, best thing to do if the image doesn't show up within about 20 seconds is restart. That usually kicks it through, so there is probably room for improvement on the fetching front.

The problem is there is no progress available for fetching images because the client has no idea how long it will take. It has to ask around a bit (and those asked, continue to ask on your behalf) until a peer with the image is discovered, at which point you download the image from them which takes basically no time at all.
