### ISSUE TITLE
[Feature] Torrent File

### ISSUE THREAD

**Issue by David-Beetle** [ssbc/patchwork#1144]
**Feature**: Add Torrent Files to Release Page (preferably with i2p trackers)
**Why?**: Decentralization

**Comment by black-puppydog** [comment]
I'm against this.
Not out of principle; distributing in a decentralized fashion is nice.
It's just that this would probably add overhead because we'd also have to seed every one of those torrents. They might include web seeds, but if you only have those then what's the point?
So this would add overhead to the organization. 

And the use case for this is "people who care enough about anonymity to not want to hit download on github, and are technical enough to use torrent instead, but don't want to just git clone (which is decentralized, in a way) and run off npm.
I don't think that's a huge group. Change my mind....
On the other hand, it might be cool to have a hook somewhere that automatically pushes all merged commits to git-ssb...
