### ISSUE TITLE
Update electron (electron 4 is EOL)

### ISSUE THREAD

**Issue by Powersource** [ssbc/patchwork#1198]
So electron 4 was released in December, but they're ending support already apparently https://electronjs.org/blog/electron-7-0#end-of-support-for-4xy

**Comment by ndarilek** [comment]
Would love it if this was fixed. I'm blind, have wanted to use SSB for a while, and for a whole host of reasons, accessible GUI apps are easier to use than command line apps in certain situations. Until fairly recently, Electron/Chromium have been inaccessible under Linux, but ever since 6 or so that has changed. It's still a bit rocky, but should be good enough for me to use something like Patchwork.

Thanks! Looking forward to putting this through its paces when it hits master, and to contributing back accessibility fixes.

**Comment by christianbundy** [comment]
Thanks @ndarilek! I've got Patchwork upgraded to Electron 6 in #1199, just waiting on some more feedback before a merge. A brief warning though: I think Patchwork has some big accessibility problems that may not be resolved with the Electron 6. To be candid, the accessibiltiy prob

**Comment by ndarilek** [comment]
Your comment re: accessibility got cut off. Not sure if you meant to 
write more.


However, I tried launching Patchwork by appending 
"--force-renderer-accessibility" to the start script, and it didn't 
work. On a whim, I bumped the Electron version to 7.1, tried again, and 
it works nicely! At least in so far as I can read the contents with 
Orca--I'm sure I'll need to make some tweaks, but this is a significant 
improvement over nothing at all. :) Had some issues when I attempted 
bumping the version from 4 to 6 a month or so back, but the bump from 6 
to 7 seems to work.


Any reason 7.1 wasn't used? Was 6.1 what was out when the PR landed? 7.1 
at least launches, so it may be a worthwhile upgrade.


In any case, I'll start looking for accessibility improvements to 
contribute.

**Comment by christianbundy** [comment]
Oops, sorry -- I accidentally posted early and then edited it in the GitHub UI.

Electron 7 worked fine in my testing, but all of the cryptography functions were very slow because our libsodium native modules don't yet support the latest Electron ABI. When this happens we fall back to JavaScript cryptography, which is slower, so generally we've tried to avoid releasing any versions without native module support.

If you see "falling back to JavaScript cryptography" or similar in the command-line output, it's almost always because the modules we're using don't support the latest Electron ABI.

**Comment by ndarilek** [comment]
OK, that's fair. I'll try making accessibility improvements and will 
keep the Electron 7 change local.


Quick question while here, slightly related to accessibility. Would you 
mind pointing me to where the general shape of the main page post-launch 
is rendered? I.e. where the menu, feed, etc. is rendered? I'm sure I can 
trace the flow better once I've found the entrypoint, but I'm not 
familiar with this particular view framework and am trying to get a few 
quick a11y wins under my belt.


Thanks, I'll stop co-opting this issue now. :)
