### ISSUE TITLE
Leaving, exiting, disconnect from a Pub

### ISSUE THREAD

**Issue by thebalaa** [ssbc/patchwork#1336]
I joined a pub and would like to disconnect from it and flush the associated content it sent me. Is this possible via the current patchwork UI?

Thanks!

**Comment by black-puppydog** [comment]
Hi @thebalaa,
if i understand correctly you want to not receive updates from that pub any longer, and delete the content that you would *not* have synced if you never followed it?

short answer: no we don't have that, and it's unlikely to be added.

long answer:
I don't think we have a way of doing this, and it would be complicated to build. 
Mostly because patchwork is built around flumedb, which is an *append-only* log file. So deleting stuff from that file, while possible, breaks things in complicated ways. We have a mechanism to zero out content from blocked feeds. So you don't save space in that case, but you don't host that content anymore. But building this logic of "would I have synced this if I wasn't following the pub?" is quite involved.
