### ISSUE TITLE
Error on `npm start` from clean build on NixOS

### ISSUE THREAD

**Issue by fabianhjr** [ssbc/patchwork#1373]
Did a `git clean -fdx`, `npm install`, and `npm test` beforhand: 

```
npm start

> ssb-patchwork@3.18.1-beta.1 start /home/fabian/Development/Open/patchwork
> electron index.js

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/fabian/Development/Open/patchwork/node_modules/electron/dist/electron ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/fabian/Development/Open/patchwork/node_modules/electron/dist/electron',
  path: '/home/fabian/Development/Open/patchwork/node_modules/electron/dist/electron',
  spawnargs: [ 'index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-patchwork@3.18.1-beta.1 start: `electron index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@3.18.1-beta.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fabian/.npm/_logs/2021-01-16T23_25_23_337Z-debug.log
```

**Comment by black-puppydog** [comment]
Hi @fabianhjr, thanks for reporting!
Nix is super difficult for me, since I only grok in veryvery general terms how it works.
But googling for this error, it seems to be quite common when trying to run electron apps on nixos. There seems to be some issue with loading native libraries.
As I said, I don't grok nix and don't have the bandwidth to set a machine up for that (last time I tried I failed miserably after a few days) so I won't address this myself directly. But of course I am happy to accept patches, and will offer what little understanding I can contribute.
One comment that seems to have found a solution for a similar problem: https://github.com/flowtype/flow-bin/issues/62#issuecomment-522208557

Of course, if there is a way we can package more cleanly for nix, then again: happy to merge patches for that.

**Comment by fabianhjr** [comment]
Upon investigation from the patchelf pointer on the flow what worked for me was to remove the npm electron binary and link to a systemwide electron nix build:

```
cd node_modules/electron/dist/
rm electron
ln -s /nix/store/wlz28fngmqq9kjl9615icji914byfd4s-electron-7.3.3/bin/electron electron
```

Thanks for the help, it seems like it is caused by missing runtime libraries (and the nix distributed electron is properly linked to its runtime dependencies)

**Comment by black-puppydog** [comment]
That's great news @fabianhjr!
If I understand correctly, the packaging for patchwork in Nix happens here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/ssb-patchwork/default.nix

I'm sure a patch there would be appreciated, if you feel up for that.
If there are changes we can make here to facilitate easier builds there, let me know!

**Comment by fabianhjr** [comment]
Yeah, but that grabs the appimage and doesn't build from source.
