### ISSUE TITLE
Reduce CPU/battery usage

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#183]
Two items we can do to conserve cycles a bit:
- Pause gifs when theyre not on screen, and when PW isnt focused
- Reduce the sync frequency, it's a bit overzealous atm

**Comment by dominictarr** [comment]
yeah, for sync, what we could do when the user is not looking at patchwork deprioritize syncing,
and then have a catchup mode that would spin up when you go back to the app. This can be when I get to the gossip refactor.

**Comment by k4ml** [comment]
Since Patchwork will cause my macbook air to scream, I can only open it in for a while then quickly quit. But there's a lot of old posts that already being synced I haven't go through yet. It would be great if there's pause button so I can read the old posts at peace.

**Comment by mmckegg** [comment]
@k4ml Sounds like #646 (add offline mode) would be helpful for this!

Either that or just wait it out sometime when the laptop is plugged in to the power and not on your lap 🤣 🔥 💯

**Comment by almereyda** [comment]
Since patchwork is considered the default application to interact with the SSB network, as of https://www.scuttlebutt.nz/, this issue could be prioritised more. The process tree shows me that Patchwork's electron is eating up all system resources upon initial sync with a pub, which also takes ages, and probably also afterwards.

This is a reason not to use SSB for me, despite I guess actual developers within the network are using much less resource-intensive ways of connecting to it.

**Comment by mmckegg** [comment]
The initial sync is always going to be the hardest part, but there is a lot of new work going into optimising this (since this is an absolute show stopper on mobile).

This issue is not about initial sync performance though, it is about standard battery use once everything is running. A lot of improvements have been made to prevent patchwork from being a major drain on battery life (outside of initial sync), and I don't find it to be a problem with day-to-day use.

I'm going to close this issue. Feel free to continue discussion about initial sync [here](https://github.com/ssbc/patchwork/issues/895).
