### ISSUE TITLE
minimum viable app proposal

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork#19]
The goal here is not to create the perfect solution to apps, but just to get an app model that can bootstrap better models.
- Each app is a single static javascript file (browserifyied by the developer, probably)
- Each app runs as a "tab" in a webview, with a name.
- Each user has a local appDb, mapping `appname->hash`.
- Apps have permissions to access different apis. access to fs, net, internal apis, are all configurable in permsDb
- Permission to access appDb and permsDb are in permsDb so you can have app and permission managing apps. With this, we can bootstrap better app managing mechanisms.

We don't need to figure out a sophisticated app model, with updates, etc, that is just part of the app manager app.

**Comment by pfraze** [comment]
I think we can create a simple base model that does have updates.

 - Every user has a namespace of files.
 - The namespaces are updated with `type: site` messages, which add or remove files.
 - When you navigate to a user's ID, you open their latest `./index.html`.
 - Each user has a local namesDb, mapping `user_petname->pubkey`

This way, the user-id represents a persistent application.
This also uses the existing HTML application conventions, rather than creating a new one with JS bundles.

The rest would work as you propose:

 - Apps have permissions to access different apis. access to fs, net, internal apis, are all configurable in permsDb
 - Permission to access appDb and permsDb are in permsDb so you can have app and permission managing apps. With this, we can bootstrap better app managing mechanisms.

**Comment by dominictarr** [comment]
The problem with the user sites proposal, i think, is that it's less bootstrappable, because it requires some structure which then must be preserved. for example, adding some sort of collaboratively edited applications would be difficult, because it would still have to be published from one feed.

On the otherhand, given a simple, single attachment based app, then you could implement a user-sites model, as well as a collaborative model.

**Comment by dominictarr** [comment]
Also, the user sites model is coupled to ssb, but my proposal is not.
You could use it on it's own or to build some other app store app.
That is a very good sign that it's a good idea.

we could make the app an html file instead of a javascript file, it doesn't really matter. to use a javascript file it would just mean a very simple html wrapper, so that the js file is injected into a script tag.

**Comment by pfraze** [comment]
Hm. No better way to find out if we *do* need a structure builtin than not to have it.

Ok, I'm on board. Let's go with the single JS file.

One of the first ones we'll need to write will inject another JS from the FS, so we can do dev.

**Comment by bhaugen** [comment]
I'm a little confused. Can't ask on Patchwork, because I can't get to run today. (Disconnects, I think on Over Quota problems: see #224).
Let's see if what I think I understand is correct:
* Patchwork apps have been delegated to https://github.com/ssbc/brickhouse
* Brickhouse is a "Security-focused electron project"
* but you are thinking about moving away from Electron.

Correctamento?

I ask because I am looking for a base for networks of [Value Flows native apps](https://github.com/valueflows/valueflows/wiki/What-we-think-Value-Flows-might-be-used-for#networks-of-apps-interacting-with-one-another) and @ahdinosaur keeps pointing me to Patchwork. I joined Patchwork yesterday, and am very impressed (despite its not working today, shit happens), but have tons of questions. This is one.

**Comment by pfraze** [comment]
@bhaugen this is a pretty old issue, we started on that coarse of action but decided to stay focused on the patchwork application alone. We're only now just circling back at this apps thing, so we may diverge from this thread and brickhouse, not sure

I'll respond to your other issue, we need to get you back online!

**Comment by mmckegg** [comment]
RIP apps, one day 🌤  Closing!
