### ISSUE TITLE
Problem with incremental build

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork#273]
When I run build:js or build-release:js, I often get this error in the browser on load:
> We're sorry! Patchwork experienced an error while loading.
>
    TypeError: undefined is not an object (evaluating 'require("../package.json").version')

The code `require("../package.json").version` is from the `elliptic` module, and it seems that browserify or browserify-incremental have trouble resolving it sometimes.

I can get around this is by deleting `browserify-cache.json` and having a slow build. I have tried with browserify 13.0.0 and 12.0.0.

**Comment by pfraze** [comment]
ah... that is weird and unfortunate, especially because 1) it doesnt happen to me, so that's weird to reproduce, and 2) slower build

hm. we can either ditch browserify-inc, or add a "--clean" flag to the build steps to optionally clear browserify-cache.json. I figure the latter is better since it does seem to work sometimes...

**Comment by clehner** [comment]
If it's just me, I wouldn't bother adding a special case. I wanted to post this here in case other people experience the same issue. I will see if I can fix the underlying thing in browserify. Also I am trying out using watchify for incremental builds, which I find to be pretty fast.

**Comment by pfraze** [comment]
ok, let me know what you find (including w/watchify)
