### ISSUE TITLE
hung server

### ISSUE THREAD

**Issue by substack** [ssbc/patchwork#407]
I'm running patchwork on an RPI3 and it loads sometimes, but often the http server does not respond. The CPU is at 100%, but it sucks that whatever it is doing is blocking the UI and http server completely. Could this be split out into separate processes or perhaps there is a spot that could use a `process.nextTick()` to keep patchwork from getting stuck?

**Comment by dominictarr** [comment]
there a few places where patchwork is a bit mean to the database, you might have more luck with https://github.com/dominictarr/patchbay

**Comment by clehner** [comment]
This is because Patchwork indexes the DB at start. You have to wait for it to say done loading indexes. Using process.nextTick to permit requests so be handled during indexing would be good. Also it would be good to refactor so the indexing is persisted using streamview-links, or ssb-links & ssb-query.

**Comment by mmckegg** [comment]
This has been greatly improved by #425. Closing!
