### ISSUE TITLE
We need to choose a license for Patchwork

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#41]
None has been chosen yet. Do we want something more restrictive than MIT?

**Comment by dominictarr** [comment]
maybe patchwork should be GPL? it's a application, not a library. that is quite different.
the Mozilla Licence is also a nice compromise between the two...
the modified parts of the core application must be published, but additions don't need to be.

**Comment by ahdinosaur** [comment]
i recently wrote up a [rundown of all license strategies i'm aware of](https://github.com/valueflows/valueflows/issues/49#issue-110579577), maybe it's helpful here.

**Comment by pfraze** [comment]
Thanks, @ahdinosaur.

So, an MIT license would let some group take the source code, make changes, and give it to their clients without the source, right? The point of the GPL is to say, you *have* to keep this open source.

**Comment by ahdinosaur** [comment]
> So, an MIT license would let some group take the source code, make changes, and give it to their clients without the source, right?

right.

> The point of the GPL is to say, you have to keep this open source.

yes. however in the context of a network application, it's recommended to use AGPL, since according to the GPL it's possible to get around having to open source your modified versions if the application is accessed over a network.

for a project like this (and [my own projects](https://github.com/holodex/app/blob/master/LICENSE)), i'd recommend copyleft (AGPL) and probably loose copyright since it's easier, i.e. [what zmq champions for](http://zguide.zeromq.org/page:chapter6#Licensing-and-Ownership) dubbed ['C4'](http://rfc.zeromq.org/spec:22) where it's intentionally impossible for anyone to later change the license.

my dream license is the [mythical "peer production license"](https://www.loomio.org/d/sKCNdenw?page=1#comment-244598), where:

>
-  if you are using the software to build open source software, you may use it for free like a copyleft license
- if you are a not-for-profit or worker-owned business, you may use it for free like a copyfarleft license
- if you are a “project member”, you may use it for free like a like a reciprocity license
- if you are using the software to build any closed source software, are for-profit, and are not a “project member”, you must share a percentage of your revenue like a reciprocity license

**Comment by reqshark** [comment]
> for a project like this (and my own projects), i'd recommend copyleft (AGPL) and probably loose copyright since it's easier, i.e. what zmq champions for dubbed 'C4' where it's intentionally impossible for anyone to later change the license.

look at the what the original author of ZeroMQ did after he left the project and completely rewrote that networking protocol simplified using only C (not C++):

http://nanomsg.org/documentation-zeromq.html

http://250bpm.com/blog:15

**Comment by reqshark** [comment]
btw i think reciprocity license sounds difficult to maintain and goes against internet freedom ideas

**Comment by mixmix** [comment]
I think ensuring open-ness of code is vital to the mission.
This is an area I need to upskill in. Thanks for the summary @ahdinosaur !

**Comment by pfraze** [comment]
Similar to @ahdinosaur's peer-production license, we've been talking about a dual license. Free for personal use, paid for commercial use. Would also like a copyleft protection (stronger than MIT). For reciprocity, could award commercial licenses to businesses that contribute to the project.

**Comment by substack** [comment]
I think GPL or AGPL seems pretty good since patchwork is an application. The underlying libraries are all liberally licensed, so people who want to use patchwork infrastructure for possibly commercial purposes have a good place to start.

As for the question of how patchwork/ssb can become a sustainable cooperatively run project, the wordpress/ghost model seems good: charge for running pub servers as a service to increase availability. From there you could also run other ancillary services that hook into ssb like build/CI tools, data wharehousing, or other things that have an inherent cost under a p2p architecture.

**Comment by aredridel** [comment]
Practically speaking, I've never seen an MIT-licensed user-facing application turned commercial by anyone. I'm not sure that actually happens in the world -- too much pressure to brand, for sure, and control user experience.

**Comment by pfraze** [comment]
Done, we used GPL
