### ISSUE TITLE
Patchwork can no longer be run from the browser ?

### ISSUE THREAD

**Issue by fredhampton** [ssbc/patchwork#435]
Patchwork can no longer be run from the browser ?

**Comment by ahdinosaur** [comment]
hey @fredhampton.

the _just released_ Patchwork v3 runs as an electron app, which means it runs in a bundled browser rather than your normal browser. what's your use case for using Patchwork in the browser?

if you want to run Patchwork in the browser, we accept pull requests! or you can continue using the deprecated [Patchwork Classic](https://github.com/ssbc/patchwork-classic).
