### ISSUE TITLE
track "read up to" state in interface

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#443]

**Comment by dominictarr** [comment]
This was also brought up on ssb recently `%yFHkDx5jir+C/BINg6XIuNgLVG9/Wmj2FEGmVuRldg8=.sha256` I understand the specific request was for unread/read state.

Since you say "read up to" I'm guessing you mean something like a "red line" as you see in irc clients. (I was also thinking this for patchbay)

**Comment by mmckegg** [comment]
This is handled pretty well by the "unread" "new" stars that have been in patchwork for ages. Gonna close this.
