### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/patchwork#466]
```
TypeError: Cannot read property 'content' of undefined
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/patchcore/message/async/name.js:21:23
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/patchcore/sbot.js:106:31
    at Object._requests.(anonymous function) (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:37:5)
    at PacketStream.destroy (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:73:66)
    at PacketStream.write (/home/dinosaur/repos/ssbc/patchwork/node_modules/packet-stream/index.js:131:41)
    at source (/home/dinosaur/repos/ssbc/patchwork/node_modules/muxrpc/pull-weird.js:43:24)
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-goodbye/endable.js:6:7
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-through/index.js:31:16
    at /home/dinosaur/repos/ssbc/patchwork/node_modules/pull-through/index.js:31:16
    at source (/home/dinosaur/repos/ssbc/patchwork/node_modules/pull-pair/index.js:21:7)
```

which led to Patchwork hanging. i'm not sure why this happened, hmm.

**Comment by ahdinosaur** [comment]
hasn't happened again, will re-open if it does come back.

**Comment by chejazi** [comment]
This is happening to me on a fresh install.

**Comment by chejazi** [comment]
It's now working after leaving it for a while (in error state) and restarting.

The only perceived difference is that my pub is no longer `ssb.rootsystems.nz`, but `ssb.joelmello.com` and `pub.mixmix.io`

**Comment by mmckegg** [comment]
I think the error you were experiencing is actually this one (different stack trace): https://github.com/ssbc/patchwork/issues/569

This is a known issue in 3.6.2. Hence the warning on the release page.

It is caused when replies have been downloaded for a message that hasn't yet been downloaded. [Fixed in the latest master](https://github.com/ssbc/patchwork/commit/325f8a3ff6e77b698f12d57000eba1859fe1364d). We need to publish a new version.
