### ISSUE TITLE
Change "like" back to "dig"

### ISSUE THREAD

**Issue by adamnovak** [ssbc/patchwork#486]
I liked the old UI a lot, and one of the things I liked about it most was the little two-fingers icon and the "dig" terminology for posts that you enjoy.

The current UI should be changed to say "Dig" instead of "Like".

**Comment by ahdinosaur** [comment]
> The current UI should be changed to say "Dig" instead of "Like".

"should"? could maybe.

yeah, well, you know, that's just, like, your opinion, man. :wink: 

- to create your own interface with all your favorite opinions, check out [`patchcore`](https://github.com/ssbc/patchcore).
- for a more customizable interface (where maybe this can be configured with `depject`), check out [`patchbay`](https://github.com/ssbc/patchbay).

**Comment by ahdinosaur** [comment]
for more context: the reason we changed from "Dig" to "Like" is that @mmckegg, the primary developer and maintainer of Patchwork, wants Patchwork to be "mainstream-compatible", so less configuration and more opinions baked in.

if anyone thinks we should discuss this rather than close the issue, i appreciate feedback. as a support maintainer here, i just want to avoid [bikeshedding](http://bikeshed.com/), and this seems really ripe for that.

:heart:

**Comment by ahdinosaur** [comment]
see also https://github.com/ssbc/patchcore/pull/9

**Comment by dominictarr** [comment]
@mmckegg you sell out! but worse, did you change the UI label without changing the "expression" field (which is to represent what you actually put on the button, which I added when I made patchbay say "yup") at least make the expression be what it says on the button.

**Comment by dominictarr** [comment]
yup

**Comment by mmckegg** [comment]
@dominictarr oh yeah, you're right! haha! Talk about lazy!
