### ISSUE TITLE
Zenity Dependency

### ISSUE THREAD

**Issue by ghost** [ssbc/patchwork#490]
Just a note that my new installation of Lubuntu (Ubuntu 16.10) complained about missing Zenity (which I assume provides Xdialog and kdialog, the other complaints that were noted) when starting Patchwork-3.3.1-x86_64.AppImage.

Apt-get install zenity cleared the problem.

**Comment by gergelypolonkai** [comment]
Zenity is actually required by AppImage (e.g. to pop up the small dialog asking if you want to integrate this app with your desktop). It might worth it to try opening an upstream bug there so they bundle something like XDialog in case everything is missing, but that might mean 88-796 kB extra on *any* AppImage package. Otherwise, the only thing one can do is showing this dependency on the documentation.

**Comment by christianbundy** [comment]
Looks like the author deleted their GitHub account as well. I'm going to close now, thanks for explaining that above @gergelypolonkai.
