### ISSUE TITLE
Number pad enter key does not work in search bar

### ISSUE THREAD

**Issue by soggypretzels** [ssbc/patchwork#534]
If you enter a search term in the search bar, pressing the number pad enter key has no effect. I expected the behavior to be the same as when I press the standard enter key.

**Comment by mmckegg** [comment]
[search.js#L26](https://github.com/ssbc/patchwork/blob/master/modules/app/html/search.js#L26) should be changed to `ev.key === 'Enter'` instead of `ev.code === 'Enter'` and then it should work as expected. 

`ev.code` is specific to the keyboard hardware itself whereas `ev.key` is the abstract locale version that handles things like multiple keys that do the same thing.
