### ISSUE TITLE
Support for mobile devices?

### ISSUE THREAD

**Issue by daviddahl** [ssbc/patchwork#56]
Sorry to ask a question founded in ignorance, but can patchwork be run on mobile devices? If not why not? Any long term plans for this? What sub-project(s) would need work?

**Comment by pfraze** [comment]
No worries, good question.

We don't currently build for mobile, because we lack the resources for it. (We're presently working on a new V2 of Patchwork's frontend, which will be our stable longterm application, and that takes all of our time.)

Our longterm plan is to adapt Patchwork to run on mobile. We'll need to answer a few different questions, including:

 - How does SSB do for bandwidth-usage? battery-usage? disk-usage? Do we need to tweak the algorithms to fit mobile better?
 - What needs to be done for Patchwork to be ported to mobile? Can we manage both builds in the same repository?
 - What platform rules, for iOS and Android, do we need to conform to?
 - How will identities work? There's currently a hard constraint, that you cannot use the same keypair on two different devices, because this can produce conflicts in SSB's data-model. We'll need to solve this. (Discussed here https://github.com/ssbc/scuttlebot/issues/252)

**Comment by daviddahl** [comment]
Thanks. I agree perf testing is the first thing to do.

**Comment by pfraze** [comment]
Relevant:
https://github.com/benoitvallon/react-native-nw-react-calculator
Creators thoughts: https://news.ycombinator.com/item?id=10513241

**Comment by dominictarr** [comment]
The perf is probably okay - that is to say, it will work - perf can always be improved, but what we really need first is something working, and for that we need someone with some mobile experience. @pfraze and I barely own cellphones.

**Comment by du5t** [comment]
Does anyone involved already have pre-existing knowledge about the compatibility of react-native with the libraries ssb+patchwork relies on? I'm assuming that anything in the client/server JS sphere will "probably work" without too much trouble; i.e., anything that can be brought in with npm and bower.

**Comment by dominictarr** [comment]
@du5t the tricky parts are probably leveldb and sodium. There is definately something for leveldb, but less people use sodium.

**Comment by du5t** [comment]
Thanks for that. I would have expected the reverse, but at least this way I know what will be a slog.

**Comment by jtremback** [comment]
I think posted this on patchwork already, but https://github.com/tradle/react-native-level and https://github.com/mochtu/libsodium-ios

**Comment by mmckegg** [comment]
lite-client patchbay seems to be the way forward on this issue for now. Closing!
