### ISSUE TITLE
More obviously distinguish between an original message and a reply

### ISSUE THREAD

**Issue by trosel** [ssbc/patchwork#581]
When scrolling through a thread, it is difficult to distinguish what is an original message and what is a message replying to something else.

Some ideas:
* indent the replies
* make first messages one color, replies a different color, follow a gradient as you see a reply to a reply, etc

It's possible that I'm not understanding the app correctly, though, so maybe I am not understanding how threads work.

**Comment by mmckegg** [comment]
Patchwork currently only emphases the original post. This will always appear first and has a slightly larger font size on the heading.

Are you talking about nested replies?

The thread is currently ordered by posted date rather than reply-to, more like a forum as opposed to something like reddit. But it is tracking when posts are direct replies and then displaying a link to the post. It would be possible to display this nested instead. I'm open to this discussion 👍

**Comment by WildYorkies** [comment]
@mmckegg I think the forum style is fine (changing to nested wouldn't be bad either, but that's a big topic I'm sure).

I'm referring to the visual look of the replies. As you scroll down, all of the blocks look exactly the same.

Fixing this could be as simply as changing the background to gray so that each post is more of an individual card and the reader can then visually see where one card starts and stops.

Or you could change is so that *all* replies are indented the same amount. That way the original post would be on the far left and it would be clear that all replies are indented. At least this way you could quickly see where original posts start and stop as you scroll down.

**Comment by mmckegg** [comment]
Hmm, there is already a gap between topics, and lines between each reply? Do you think this is not enough separation?

<img width="763" alt="screen shot 2017-07-08 at 5 31 52 pm" src="https://user-images.githubusercontent.com/66834/27982889-72d42a84-6403-11e7-80ab-edccbf7da612.png">

<img width="791" alt="screen shot 2017-07-08 at 5 31 45 pm" src="https://user-images.githubusercontent.com/66834/27982892-7a1061f0-6403-11e7-8113-945d279a51f7.png">

**Comment by mmckegg** [comment]
Interesting. I just saw this on a different computer, and you really can't tell that there is a different coloured background or line between.

@WildYorkies can you look at http://www.lagom.nl/lcd-test/white.php#whitetest.png and tell me how many of those you can see?

On my laptop (which I primarily use), I can see 11 of them (all except the last). But on this linux machine, I can only see the first one. The rest appear fully white.

Both my laptop and linux box are plugged into the same monitor. :cry: 

I wonder how common this is?

**Comment by WildYorkies** [comment]
@mmckegg On this tv, if I turn "adaptive contrast" off, I see about 8. If I turn "adaptive contrast" on, I see 11.

On a Lenovo laptop I see ONE of those boxes haha
