### ISSUE TITLE
It takes a long time to download new messages

### ISSUE THREAD

**Issue by spaceywolfi** [ssbc/patchwork#643]
Once I connect to 1 pub it takes a long time to download all the messages. I assume that this will take even longer in the future, and probably it will never stop downloading new messages once there are enough people on the network.

Could it be possible to only download the list of users / streams from the pub and then if i am interested for the stream # scuttlebot i can subscribe to that stream and only download content from that stream. 

Also since it is a log that keeps on growing i am wondering if it is possible to just stop replicating very old data that is not so relevant anymore. (maybe people can take snapshots to preserve the data somewhere)
it would be cool to be able to customize how much data should be downloaded from a specific stream / person. I am not sure if this would be possible with the append only log.

Again I am not exactly sure what is possible, but maybe at least prioritizing downloading messages from streams that are subscribed would be cool

**Comment by spaceywolfi** [comment]
im also wondering if there is anyway to stop being connected to any pubs, it seems once i am connect to a pub i can never disconnect (unless i turn of my wifi)

**Comment by mmckegg** [comment]
@spaceywolfi Right now you download 3 degrees of feeds (friends-of-friends-of-friends) from whoever you follow (most likely a pub in your case). Because most pubs are connected to other pubs, this usually gets you the entire network which is not going to scale for the reasons you mentioned above.

We want to reduce this down to 2 degrees (friends-of-friends) which would reduce the number of feeds to download greatly. The reason this has not been done is that it would mean you would not see as many replies to conversations. There would be a lot more missing posts.

This will be addressed in the future by "out-of-order-messages" which @dominictarr is still working on adding. This will mean that you can download individual messages from people who you are not friends with and allow you to see their replies in threads that your friends create.

---

A"quick" hack I've been thinking about to improve this situation is to allow exporting an "onboarding" pack that contains a bunch of feeds prepopulated (via a friend or pub). It can be compressed and downloaded as a single file. Should be much faster.

This could be automated as part of "request an invite" from a pub or shared with your friends directly.

**Comment by spaceywolfi** [comment]
oh that sounds very reasonable, thank you for you reply!

Maybe it could make sense in a home server setting to have all the data of the third degree there and be able to connect your laptop and phone to that home server to have all this data, otherwise just use the second degree would be used.

also i realized that if i unfollow the pub the message "downloading new messages" is stuck and does not download new content, but the message does not dissapear, should i make a seperate issue for this?

**Comment by mmckegg** [comment]
@spaceywolfi Yeah the stuck "downloading new messages" is a bug that I've seen pop up a few times. Think it is a display bug rather than an actual deep problem. 

I thought there was an issue for it, but I think it was on a related thread that was closed. Go ahead and make one if you want!

**Comment by pjv** [comment]
hi @mmckegg,

I'm newly looking at SSB and trying to understand it architecturally. When you say this:

>Right now you download 3 degrees of feeds (friends-of-friends-of-friends) from whoever you follow (most likely a pub in your case). Because most pubs are connected to other pubs, this usually gets you the entire network which is not going to scale for the reasons you mentioned above.

am i correctly understanding that to mean that if you connect (via patchwork) to 1 or 2 well-connected pubs you essentially end up downloading virtually all of the content in the entire SSB network?
