### ISSUE TITLE
Scroll to bottom when clicking "view full thread" isn't user friendly

### ISSUE THREAD

**Issue by itsrachelfish** [ssbc/patchwork#650]
As a new user I haven't read any of the messages in a thread, so automatically scrolling to the bottom isn't very user friendly. I have to click "view full thread" and then scroll all the way back up to the top!

I understand if you've been on the network for a while and you've already read every post it makes sense to scroll to the bottom, but it would be nice if my client kept track of what messages I've read and scrolled to that point.

Related to: #443

**Comment by mmckegg** [comment]
@itsrachelfish Yeah, I've been wondering about this.

This stuff is rather hard to balance. Full thread used to always go to the top of a thread, but this was a pain for finding your place in large threads especially if the most recent messages were long. So I recently changed it to scroll to just above the most recent 3 messages that were displayed in the feed so that you could read backwards to find where you were up to.

I agree that it would be nice if it was smart enough to drop you were you most recently read up to, but that will require a lot of reworking and state tracking to make happen. I will give this some thought.

Quick tip: If you click on the timestamp for the first message instead of "View full thread" it will go to the first message and not scroll down.

**Comment by mmckegg** [comment]
@itsrachelfish 

I just updated the behavior so that it now scrolls to the start of the first reply. This will be in the next release. Thanks for your feedback!!

I decided that the case of the most recent messages could be handled by clicking the timestamp of the recent message and then using the "view full thread" presented on the individual message. Good enough to solve my workflow problem, and it's no longer confusing for new people.
