### ISSUE TITLE
What are the similarities and differences between Patchwork and "Rotonde" 

### ISSUE THREAD

**Issue by fredhampton** [ssbc/patchwork#651]
There is a new beaker based messaging app "Rotonde" https://github.com/Rotonde/beaker

What are the similarities and differences between Patchwork and "Rotonde" 

Thanks !

**Comment by WildYorkies** [comment]
This is literally all opinion from a passerby. Take it with much salt.

In order to properly compare, you'd have to compare Secure-Scuttlebutt to Dat protocols.

https://www.scuttlebutt.nz/concepts/ vs https://docs.datproject.org/concepts

The biggest difference at a fundamental level is that SSB was created with a social network in mind; Dat was created with a better file storage in mind.

This means that SSB and Dat have thought through and solved different problems better than one another. But having said that, I'd like to see SSB move over to Dat because I think the Dat system probably has a more mature codebase and way more funding. And the robust file storage ideas are more important as a foundation.
