### ISSUE TITLE
Threads in public stream repeat over and over

### ISSUE THREAD

**Issue by bhaugen** [ssbc/patchwork#685]
I'm using Patchwork-3.8.1-x86_64.AppImage on Ubuntu 16.04. The same threads repeat in different sequences many times. It's not the same thread repeated immediately, but repeated again later after some other threads, and then repeated again later after some other threads, never in exactly the same sequence. Often takes a lot of scrolling to get to anything different from the sequences of repeated threads.

**Comment by mmckegg** [comment]
@bhaugen 

Yep, this has been fixed in latest master. Identified here (at bottom): [%sHO75FSTtwB9YFYngVeU3LZkwqEAnehymGY9dDghVVw=.sha256](https://viewer.scuttlebot.io/%25sHO75FSTtwB9YFYngVeU3LZkwqEAnehymGY9dDghVVw%3D.sha256)

We should push out a new pre-release ASAP. 

---

@ahdinosaur if I create a tag can you build and upload?

I still have too many issues left to officially release, but since 3.8.1 has become sort-of official thanks to that infinite loading bug in 3.7.x, we probably should get this out!

**Comment by mmckegg** [comment]
Released! https://github.com/ssbc/patchwork/releases
