### ISSUE TITLE
Mentions are out of order since upgrading to 3.8.6

### ISSUE THREAD

**Issue by jnny** [ssbc/patchwork#722]
After upgrading to Patchwork 3.8.6, my Mentions are now completely out of order, making it incredibly frustrating to find posts I've been tagged in and locate ongoing conversations:

![screenshot from 2018-01-08 15 16 04](https://user-images.githubusercontent.com/1790886/34697238-115bf38a-f487-11e7-8953-02a64e7f4405.png)

It seems I'm less connected than I was before, unable to view lots of messages in threads - like my subscribed pubs didn't fully transfer to the new version..

I'm running Ubuntu 14.04.

**Comment by mmckegg** [comment]
@jnny What version were you running previously?

**Comment by jnny** [comment]
@mmckegg - either 3.6.4 or 3.7.1, not sure :/

**Comment by mmckegg** [comment]
@jnny 

As for the missing messages, this could be because Patchwork >= 3.8 now only replicates 2-hops (friends of friends) instead of 3-hops (friends-of-friends-of-friends). The answer right now is to follow more people and you will see more content, but the more long term solution (in a month or two), will be to add support for SSB OOO (out-of-order messages) to find these posts. That will let you see posts from outside of your network that people inside have replied to or liked. This isn't quite ready yet, but once this in in place, missing messages should be a thing of the past!

As for the mentions out of order, not sure what is going on there. As far as I know, nothing has changed since 3.6.4 on the mentions page (apart from now including follow messages).

Are you running the AppImage (from the releases page) or building from source?

Have you preformed a re-sync or anything like that? Since the mentions page is ordered by **received** time (when you first found out about the message, rather than when it was written), the order can get messed up if you delete your database and re-download everything. But if you haven't done that, something else must be going on!

One thing I can think of as a hack to improve your situation would be adding an option on settings page to make the mentions page show in asserted order (the time the posts claim to have been written) instead of received time. Be nice to get to the bottom of it though!

**Comment by mmckegg** [comment]
Gonna close this for now. Anyone can feel free to reopen this if you have further ideas about how to improve this situation.

The key things I can think of that would affect this is:

- performing a resync
- changing hop size
- bumping into very old friends

I think it is important the mentions page is ordered by most recently discovered mentions (not asserted timestamp), otherwise you might miss someone coming back online after making a bunch of offline posts.
