### ISSUE TITLE
Adding an image twice doesn't work

### ISSUE THREAD

**Issue by mixmix** [ssbc/patchwork#735]
Say I attach an image, then delete it from the message.
When I try to attach the same image again, it doesn't work.

(Patchbay has the same problem)

mix thinks we should extract a `message.html.compose` module and solve a bunch of things!

**Comment by mmckegg** [comment]
This is because `onchange` on the `input` element only fires when it changes. Since you just selected the same file again, it doesn't fire again. 

It might be possible to clear the selection, or swap the element for a new one once selection has been made. I don't think that you can say `input.value = null` without throwing a security error, but I might be wrong.

**Comment by mmckegg** [comment]
@mixmix I fixed this in patchcore by adding `input.value = ''` after the blob has been processed.

https://github.com/ssbc/patchcore/commit/34a54c295b6a1f27085cf860c739fb389ea68211
