### ISSUE TITLE
Latex support with MathJax

### ISSUE THREAD

**Issue by entron** [ssbc/patchwork#786]
Is it possible to support Latex with MathJax (e.g. http://support.typora.io/Markdown-Reference/)? I think patchwork has great potential for academy people when latex support included.

**Comment by daviewales** [comment]
Can I suggest [KaTeX](https://khan.github.io/KaTeX/) instead?

It's not quite as complete as MathJax, but it's far faster.

**Comment by stripedpajamas** [comment]
I would really like this feature as well and I think it would be great for academics like @entron said.

Some work has already been done about getting KaTeX support in Marked ([here](https://github.com/markedjs/marked/compare/master...linxiaowu66:master#diff-81ab0a5aa39b7a91951fc28d2d151496)).

I think the path forward would be to put a PR in to ssb-marked to allow the LaTeX syntax and have it pass the text to a config function (like linixauowu66 did). And then put a PR in to patchcore that passes in KaTeX as that config function (in message.html.markdown: [adding a line here probably](https://github.com/ssbc/patchcore/blob/master/message/html/markdown.js#L69)).

If there's another way besides going through patchwork -> patchcore -> ssb-marked and back up, let me know... I'm guessing we could rework patchwork a little bit so that it does some parsing/rendering of its own (which potentially handles stuff like LaTeX and any other future ideas), and then passes the rest to patchcore (which passes it to ssb-marked) for htmlizing, but that sounds a little slow/bulky.

I know there has been discussion about where patchcore starts and ends ([here](https://github.com/ssbc/patchcore/issues/6))-- wondering where this issue lies. Would love to work on it if given some direction forward.

Thoughts @mmckegg (& everyone) ?

**Comment by buoyantair** [comment]
I think this is a really good feature to have :D

**Comment by mmckegg** [comment]
Patchwork is now using [markdown-it](https://github.com/markdown-it/markdown-it) via ssb-markdown for rendering and no longer depends on patchcore.

I found [markdown-it-texmath](https://www.npmjs.com/package/markdown-it-texmath), which should do the job. How hard would it be to add this @christianbundy?

**Comment by christianbundy** [comment]
Yep, I think that would be simple to add. We could either add it to ssb-markdown or make it so that ssb-markdown can be extended (see [`%U8YJGELBqdawM01T4Kpzq10VKV8ciCdKq2h2kqjevtM=.sha256`](http://viewer.scuttlebot.io/%25U8YJGELBqdawM01T4Kpzq10VKV8ciCdKq2h2kqjevtM%3D.sha256)).
