### ISSUE TITLE
Unrolling a message thread loses reply draft

### ISSUE THREAD

**Issue by madduck** [ssbc/patchwork#792]
I just composed a longer reply to a message, and then wanted to make sure to scan the whole thread one more time before sending. Unfortunately, when I clicked "show the other 18 messages", it reloaded the page and cleared out the message box, so I lost the reply draft. It'd be nice if that could be saved, or somehow restored, or I be warned that this would happen and asked for confirmation.

**Comment by mmckegg** [comment]
If you push the back button, your message will still be there. It didn't reload the page, it navigated to a new one (full thread).

The full thread view would post a reply to the main thread, not the individual message, so it doesn't make sense to move your message to the other page.

**Comment by mmckegg** [comment]
Although I have noticed a bug where sometimes the post hasn't been persisted. Might be because the view timed out (pages only persist their state for 5 minutes when not focused).

THere's a pending [PR for adding draft persistence](https://github.com/ssbc/patchwork/pull/755) which should fix this though.
