### ISSUE TITLE
How do I delete or edit a message?

### ISSUE THREAD

**Issue by bsapwindows** [ssbc/patchwork#815]
It seems the only option I have is to delete everything manually within .ssb folder. I'm sure it can't be, but I couldn't find the answer through the [guide](https://www.scuttlebutt.nz/getting-started.html)... :sweat_drops:

**Comment by cryptix** [comment]
It currently is. the only sensible thing on an append-only log is to update information that needs changing but the history will always be there.

We are getting close to mutable messages, though.

**Comment by bsapwindows** [comment]
I see. Thanks for the info. Though I feel this is the creepy part of P2P network, isn't it? Knowing whatever you said to a friend or random rants in your diary to be logged by someone forever...

Personally, I prefer the software acting like a server, so you could choose to allow your friend to log it or not. If you choose not to let them, then they can only access your "diary" when you are around, your friends won't be able to see your archived posts if you are not there, like a browser returns `ERR_CONNECTION_TIMED_OUT`; If you choose to allow them, then they'll be able to have a local copy of your diary. Kinda like implementing a robots.txt. Practically, users might modify the code or even log it manually to ignore others' preferences, but most of them won't, and those who did might lose friends because of stalking against others' will.

In addition, the software could also let a user modify others' local copies if he/she holds the private key, so a user could edit/delete a specific post from others' local database, others won't be able to see that post anymore once they received the modification request, but they'll see the owner of the post has changed something, the time he/she did it, and other metadata of that modification. This gives a user more control over his/her own content.

Not sure if I expressed myself clearly. And not so sure if such proposal is somehow against Scuttlebutt's design.

**Comment by mmckegg** [comment]
> Not sure if I expressed myself clearly. And not so sure if such proposal is somehow against Scuttlebutt's design.

Scuttlebutt is designed around the idea of assuming offline. There is no way to talk directly to other people on the network (no direct connections except to pubs and local peers e.g. on your wifi). You hear about new messages normally via pubs and then append these to your log. Each message references the hash of the previous one, and if there is any message missing, sync is aborted. If I understand correctly, what you propose is a very different system.

There is a lot of discussion on ssb about how to best support this. Hiding messages, or updating messages (with history viewable) is fairly straight-forward to support, but true purging of content is a lot more tricky.

Anyway, I'm going to close this since it is more of a question (that has been answered). One of these days we'll likely get some kind of content purging, and a method of editing/hiding posts (there is already work being done on both of these).

**Comment by tiotrom** [comment]
It is 3 years later, I am using Patchwork but can't seem to find a way to delete or edit a message. So this was not implemented after all?
