### ISSUE TITLE
Release cycle?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchwork#826]
Hello!

Is there a predefined release cycle for Patchwork? No problem if there isn't (or you aren't interested in having one), but I thought I'd ask either way.

Thanks!

**Comment by mmckegg** [comment]
Traditionally the release cycle has been release whenever there has been substantial changes or important bug fixes and we are sure that everything is working well (been running for a few days without issues off master). So I guess the answer is no! 😆 

What I'm currently waiting on for a release is:

- [ ] fix the search (#823)
- [ ] fixing a random hanging issue that only appears sometimes (sometimes scrolling to the bottom of a feed causes the loading spinner to appear for 5-10 seconds before the next data shows in the feed)
- [ ]making sure that the issues with index ordering has been solved (https://github.com/ssbc/patchcore/blob/master/backlinks/obs.js#L57 is no longer working since merging https://github.com/ssbc/ssb-backlinks/pull/7, but we should be able to use order option instead: https://github.com/flumedb/flumeview-query/pull/12#issuecomment-389735617)
- [ ] a few quick bug fixes that have issues (e.g. #808 #796)

I was away most of last month, so stuff has kind of built up. But keen to get this out ASAP!

**Comment by arj03** [comment]
Really great seeing you working on a new release @mmckegg. At network convergence I used patchwork to onboard people even if I mostly use patchbay. Its just so polished and the local nodes view is just perfect for that. So thanks! ❤️ 

Unrelated to this I recently found blocking to be partly broken atm. See https://github.com/ssbc/ssb-ebt/pull/12. I don't want to delay your release, just wanted to raise awareness. The fix is probably something that will land within a day or two. I have been testing it locally without issues.

**Comment by mmckegg** [comment]
I'm probably ready to release this. But still a little worried about that hanging issues.

Experienced it last night constantly, but today only a couple of times. I think it is when sbot is getting overloaded. Maybe I was connected to some dodgy pubs last night? Who knows!

Probably push up a pre-release tomorrow!

**Comment by mmckegg** [comment]
@arj03 still haven't added ebt to patchwork, so I suspect that it won't be affected by that bug. Thanks for letting me know though!

**Comment by christianbundy** [comment]
> Experienced it last night constantly, but today only a couple of times. I think it is when sbot is getting overloaded. Maybe I was connected to some dodgy pubs last night? Who knows!

I tried inspecting the performance of both the frontend and backend but couldn't find anything in either of those processes that matched the load lag I was triggering on the screen. The idea that it could be an sbot thing makes a lot of sense to me since it's in another process (?).

**Comment by mmckegg** [comment]
@christianbundy are you experiencing the slow scrolling problem too? I haven't had it happen for a few days now.

**Comment by christianbundy** [comment]
If I scroll fast enough sometimes the loading spinner will appear for a few seconds, but I think that's likely because I'm not on a very powerful machine. Nothing more than a few seconds though.

**Comment by mmckegg** [comment]
I hit the issue again today. I tried running the old patchwork off my running sbot and it did not have the problem. Also reloading the interface seemed to fix it.

Must be something in the client after all. Not sure where exactly. Might be in the new mux-rpc, or it could be a mutant issue.

I'm gonna publish anyway, and we'll wait and see if anyone else complains.

**Comment by christianbundy** [comment]
Weird, I'll keep poking around and see if I can get it to trigger consistently.

I noticed this was tagged as a "pre-release" -- does that mean it's ready to be deployed to package managers? I'm one of the maintainers for [Patchwork on Arch Linux](https://aur.archlinux.org/packages/ssb-patchwork/) and I'm excited to deploy v3.10, but "pre-release" hints that maybe I shouldn't. What do you think?

**Comment by christianbundy** [comment]
Nevermind, saw your response at ssb://%NvZHJLsG6ZC7OKRGBNxKnv1GDQjgdCPq0CqaK6F4mSQ=.sha256:

> Because I made a bunch of changes last minute and I'm slightly concerned I might have broke something. Instead of just waiting to see, I released it!  :grinning:
> If no one reports anything critical in the next day, I will mark it as a proper release. This is pretty standard for Patchwork releases.
> I don't like to push out too many updates in a row, so I want to avoid having to do a notified point release a day after a previous one. Trying to avoid update fatigue.

I'll close this issue and update the Arch package. Thanks!
