### ISSUE TITLE
Limit on number of recipients silently fails and freezes "private" window.

### ISSUE THREAD

**Issue by Zaijo** [ssbc/patchwork#838]
Hello there. Patchwork 3.10.1 private edit window freezes when trying to mention more than 7 recipients in a private message. Why the limit?

How to reproduce:
- Write a private message to 8 recipients.
- Check error log in Electron console.
- You get: `Error: max recipients is:7 found:8`

First thing is. **Do we need the limit?** Why is it there? Does it have something to do with the architecture of ssb?

If we need the limit, I'd like to see a warning i.e.: "Patchwork only allows 7 recipients in a private message, because <reason follows>."

**Comment by cryptix** [comment]
The limit is arbitrary but not unwarranted. You might want to consult the [private messages section of the protocol guide](https://ssbc.github.io/scuttlebutt-protocol-guide/) to learn more about how they function.

The gist is this, though: Each recipient will get an individual decryption key for a private message. Each of these adds 49bytes to a message. Apart from the size constraint (8kb per message) having lot's of recipients on private messages will also lead to lots of overhead/wasted CPU cycles for all the non-recipients of a messages. Since there are no `TO: ...` fields everybody tries to decrypt all the messages they replicate/feeds they follow. This is manageable with 7 or 8, maybe with 10 but not much higher, I fear. For larger groups we will need something like shared encryption keys.

Thanks for the report, though. Patchwork definitely shouldn't freeze over this.

**Comment by mmckegg** [comment]
Yeah, this is a bug. We'll get it fixed for the next release.

**Comment by mmckegg** [comment]
Closing as this has now been addressed in #859 and will be in the next release.
