### ISSUE TITLE
Support DHT invites

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchwork#853]
See https://www.npmjs.com/package/ssb-dht-invite

Support the DHT invites that @staltz has been working on for [mmmmm](https://gitlab.com/staltz/mmmmm-mobile)

**Comment by staltz** [comment]
This would be great! If someone makes a PR I can gladly review. Just follow the readme instructions, then make a "create invite" button that calls `sbot.dhtInvite.create`, and then another button "accept invite" which calls `sbot.dhtInvite.accept(invite, cb)`

**Comment by christianbundy** [comment]
Resolved by #862.

**Comment by espectalll** [comment]
What happened to this? Seems support was disable shortly afterwards with b473ba3?

**Comment by staltz** [comment]
Actually it would be simple to add support for these now that Patchwork uses ssb-conn, I'll see if I can do that

**Comment by grinapo** [comment]
> Actually it would be simple to add support for these now that Patchwork uses ssb-conn, I'll see if I can do that

And have you?

**Comment by staltz** [comment]
It is done. It is closed because it's done.

**Comment by grinapo** [comment]
I am sensing a weird communication here. It is done, yes, it's visible above, and it's **disabled**, as noted also above. It does not work, not useable. You said it would be simple to add and it's not added. Shall I open a new issue about "support DHT invites for the user, not just the code"? [Based on last release version since the release notes pretty much advise not to use the beta for normal use.]

The problem is that right now I don't quite see how _personA_ would connect to **his friend** _PersonB_ without subscribing any pubs (or, anything)? Or even then, how to find someone, or how to share something to make them find me? Weirdly this isn't a FAQ, or at least not on the scuttlebutt website. I can easily follow random people I do not know but I don't seem to be able to ask patchwork to follow people I *do* know.
Frustrating.

But I stop commenting the issue, but you don't seem to soo why it have happned.

**Comment by staltz** [comment]
https://github.com/ssbc/patchwork/pull/1246
