### ISSUE TITLE
How to handle media playback when changing view?

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#873]
I just noticed that changing view (e.g. clicking "full thread" on the thread holding the media *or any other thread*) the media keeps playing. Which is nice, in a way, but if I make a few clicks, then want to stop the music or whatever and cannot find it, it might be suboptimal. Not sure how best to solve this, but I thought it'b be good to be aware of.

**Comment by mmckegg** [comment]
I agree that this is a major concern and something that will need addressing.

For now, media playback is a bit of a hack on (and with the 5 MB limit, pretty.. uh limited). But, I am really keen to make media a first class citizen in Patchwork. I'd love to bring some of the [Ferment](http://github.com/fermentation/ferment) features over to Patchwork like a global player and play queues. We also need a better file transport, so that we can support larger things (> 5 MB) like actual video. Another option is to bring ferment back from the dead as the scuttlebutt media player!

A quick fix idea to make things a little better than they are: hook into the IntersectionObserver and current tab to find out what is actually in view, and stop media that goes outside. This won't allow background playback, but that probably isn't a big deal since there are currently no queues or long files anyway.
