### ISSUE TITLE
Allow switching of spellcheck language

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#942]
When composing posts in anything but English, red wiggles appear all over the place.
It would be cool to be able to switch the dictionaries, at least to the languages also supported in i18n.

**Comment by mmckegg** [comment]
I think at the moment that it should be following your system language (unless there is a deeper bug). But I agree that it would make much more sense to tie this to the interface language.

**Comment by black-puppydog** [comment]
Given that it's kinda chrome, it might be possible to *default* to the interface language, but to select at runtime, with a context menu in the text field? This is what browsers do, and it's muchmuch useful for posting in multiple languages, some of which I'm not that familiar with. :P

**Comment by christianbundy** [comment]
We have a way for people to change their language, but it looks like [we still hardcode English](https://github.com/ssbc/patchwork/blob/13f05673a919f2226ec55a4795a7cb895724cef2/lib/context-menu-and-spellcheck.js#L15). I think we should probably set this dynamically from the settings. The only complexity is that our [locale list](https://github.com/ssbc/patchwork/tree/master/locales) seems to be formatted differently from the example (like `en` rather than `en_US`) so we might need to normalize those.
