### ISSUE TITLE
Show other users on LAN

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork#99]
For CampJS (and many future occassions) we want to see a list of the users on the LAN, so that people can quickly discover and follow each other. Magic!

I believe the peerlist from the gossip plugin will include all the info we need (though I dont think the IDs which are claimed in the LAN multicast are verified yet). So we may not need sbot changes for now: just UI improvements.

So, how should we help people discover LAN peers?
Brainstorming some options:
 - A UI element in the global UX (top right corner? bottom of left nav?) which lists active LAN peers.
 - Contacts page lists all peers (pubs, LAN) at the top, and indicates the direct connectivity. If you don't have the user's feed downloaded, there's a button prompting you to download the profile. Then, you can follow them!
 - (Someday) a way to send "friend requests" to direct or proxy connections, so that, after following, you can ping them to follow you.
 - (Someday) a way to chat with direct or proxy connections -- similar to friend requesting, but a bit more general.

**Comment by pfraze** [comment]
@mixmix is going to do work on this

**Comment by pfraze** [comment]
Quick mockup of local users on the nav:

![screen shot 2015-11-25 at 6 25 46 pm](https://cloud.githubusercontent.com/assets/1270099/11412382/0231dd2c-93a2-11e5-8c7c-0ed8bdd3793b.png)

**Comment by pfraze** [comment]
Mockup of a floating panel:

![screen shot 2015-11-25 at 6 35 59 pm](https://cloud.githubusercontent.com/assets/1270099/11412558/d6d57088-93a3-11e5-86e7-fac07d83b55e.png)

**Comment by mixmix** [comment]
Sweet lateral thinking here @pfraze 
I like how it really brings this to the forefront of user attention. I think that could be a double edged sword - as in when is it useful to know who is online?  _e.g If I always share an office with Substack, that's boring, if I've visiting a cafe, or a village hub, then this could be awesome._

Furthermore, this surfaces that we might need to address the definition of Online. I think we should consider smoothing it some, so that the Online-users list doesn't become a distracting flicker of on-off.

**Comment by pfraze** [comment]
agree about smoothing. also agree about the unclear value of seeing the list. maybe as a dropdown in the top right?

**Comment by mixmix** [comment]
continuing on Patchwork thread `%qSXwvHi+x3+I6zD6thA9SLOSGJPsqrBVUDJ6KyFe/u0=.sha256`
